# Generated by Django 4.2.21 on 2025-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='scale',
            field=models.CharField(default='Likert', max_length=20),
        ),
    ]
