# Generated by Django 4.2.21 on 2025-05-13 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('carrer_url', models.CharField(max_length=255)),
                ('mission_statement', models.TextField()),
                ('core_values', models.JSONField(default=list, help_text='List of company values (e.g. Innovation, Integrity)')),
                ('culture_keywords', models.JSONField(default=list, help_text='Descriptive keywords of the company culture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
