# Generated by Django 4.2.21 on 2025-05-20 15:05

import api.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_carrer_url_company_career_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.companies.models.company_logo_upload_path),
        ),
    ]
